### ISSUE TITLE
SCIM->OpenFGA

### ISSUE THREAD

**Issue by aaguiarz** [tmuntaner/skyscraper#243]
Hi @tmuntaner

I’m the Product Manager for @OpenFGA and we just found this project. Nice work!

I see you have implemented a SCIM-> OpenFGA bridge, would you be interested in extracting that into its own independent project?

It would be a very welcome addition to the OpenFGA ecosystem, and seems like something a lot of users would want.

Thanks!

**Comment by tmuntaner** [comment]
Hi @aaguiarz,

I'm sorry for getting back to you so late, but I was on vacation for the last few weeks and stayed away from my github.

I'm not against the idea, but I'll have to see how feasible it is to generalize this functionality. If you have any MVP requirements for the bridge, I would be happy to look at them.

When I have a better idea of what we would need to do, I'll bring it up to my team.

Everything SCIM is already away from the other application logic, so it shouldn't bee too complicated to extract.

Thanks,
Thomas Muntaner

**Comment by aaguiarz** [comment]
Hi @tmuntaner 

Thanks a lot, I've seen you started it here https://github.com/SUSE-Skyscraper/openfga-scim-bridge :) 

The scope I'm thinking of for an MVP is to be able to implement the endpoints to manage the groups creation/deletion + group user membership.

I'll give the other project a try :)

**Comment by tmuntaner** [comment]
Hi @aaguiarz,

I made that repo by copying everything scim from the main application, but it still needs more tests/reviews/docs.

It's still not ready and I'll let you know when I update it again. I at least want to write down some docs and basic assumptions to see if we're on the right path.

**Comment by aaguiarz** [comment]
Thanks!

I've seen you are storing the data in a local database and also calling FGA. What's the reason for the local database?

**Comment by tmuntaner** [comment]
HI @aaguiarz,

For some background: this project was a solo hackweek project which my team will develop further after we finish some other tasks.

Our SCIM implementation came first with these database tables, then we implemented casbin for permissions, and then we removed casbin and settled on OpenFGA. OpenFGA fit our future plans and we accomplished exactly what we wanted with little fuss.

As for the database removal, I'm not sure we can remove the database and keep to the SCIM 2.0 protocol, but it can be investigated.

Notes:

* https://developer.okta.com/docs/reference/scim/scim-20/ was useful for me in my SCIM implementation.

We need to:

* Be able to create users and store their metadata.
* Be able to search for users by metadata (usually username).
* Be able to update users and their metadata.
* Be able to give users an ID and retrieve them by that.
* Be able to create groups,
* Be able to search groups.
* Be able to give groups an ID and retrieve them by that.
* Be able to list users in a group and patch its membership list.

I'm not an expert in SCIM (I just read and implemented the RFCs) nor OpenFGA (yet), so maybe this can all be solved. Either way, I'm interested in the SCIM -> OpenFGA bridge.
